language: node_js
matrix:
  fast_finish: true
node_js:
  - 12.16.3
before_script:
  - curl -L
    https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
    > ./codeclimate-test-reporter
  - chmod +x ./codeclimate-test-reporter
  - ./codeclimate-test-reporter before-build
script:
  - npm run lint
after_script:
  - ./codeclimate-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
