name: Create Release from Tag

on: push

jobs:
  release:
    runs-on: macos-latest
    if: startsWith(github.ref, 'refs/tags/')
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: yarn install
      - run: yarn electron:make
      - uses: softprops/action-gh-release@v1
        with:
          body_path: CHANGELOG.md
          files: out/make/zip/darwin/x64/*.zip
        env:
          GITHUB_TOKEN: ${{secrets.REPO_SCOPED_TOKEN}}
