name: Verify on Push

on: push

jobs:
  verify:
    runs-on: macos-latest
    if: startsWith(github.ref, 'refs/tags/') == false
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v2
      - uses: aktions/codeclimate-test-reporter@v1
        with:
          codeclimate-test-reporter-id: ${{secrets.CC_TEST_REPORTER_ID}}
          command: before-build
        continue-on-error: true
      - uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.node-version}}
      - run: yarn install
      - run: yarn lint
      - run: yarn electron:make
      - uses: aktions/codeclimate-test-reporter@v1
        with:
          codeclimate-test-reporter-id: ${{secrets.CC_TEST_REPORTER_ID}}
          command: after-build
        if: always()
        continue-on-error: true
